base: core22
compression: lzo
name: mysql-workbench-community
title: MySQL Workbench
version: 8.0.32
summary: MySQL Workbench
description: |
  MySQL Workbench is development, administration and data modeling tool
  for MySQL. Besides editing and running SQL queries and scripts, it supports
  the design of MySQL databases through a EER diagram, which is then used to
  generate SQL scripts. Workbench also supports migration from many RDBMS
  products to MySQL.
type: app
grade: stable
confinement: strict
license: GPL-2.0
icon: mysql-workbench.png
architectures:
  - build-on: amd64

apps:
  mysql-workbench-community:
    command: usr/bin/mysql-workbench
    desktop: usr/share/applications/mysql-workbench.desktop
    extensions:
      - gnome
    plugs:
      - home
      - opengl
      - network
      - ssh-keys
      - password-manager-service
      - cups-control
      - removable-media
    environment:
      PYTHONPATH: $SNAP/usr/lib/python3/:$SNAP/usr/lib/python3/dist-packages/:$PYTHONPATH
      PROJSO: $SNAP/usr/lib/x86_64-linux-gnu/libproj.so
      LD_LIBRARY_PATH: $SNAP/usr/lib/x86_64-linux-gnu
      WB_DEST_DIR: $SNAP

parts:
  config:
    plugin: nil
    build-packages:
      - curl
      - gpg
    override-pull: |
      echo "deb [signed-by=/usr/share/keyrings/mysql.gpg] http://repo.mysql.com/apt/ubuntu jammy mysql-tools" > /etc/apt/sources.list.d/mysql.list
      curl -sSL "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x467B942D3A79BD29" | gpg --yes --dearmor --output /usr/share/keyrings/mysql.gpg
      apt -qq update

  copy:
    plugin: dump
    after: [ config ]
    source: .
    organize:
      lsb_release: usr/bin/lsb_release

  install:
    plugin: nil
    after: [ copy ]
    stage-packages:
      - mysql-workbench-community
      - libcanberra-gtk3-module
      - libproj22
      - libproj-dev
      - python3
      - libc-bin

  fix-icon:
    plugin: nil
    override-build:
      sed -i 's|Icon=mysql-workbench|Icon=/usr/share/icons/hicolor/128x128/apps/mysql-workbench.png|' $CRAFT_STAGE/usr/share/applications/mysql-workbench.desktop
    after: [ install ]
